- Handle change in config file format
SUSE-Enceladus/monitoring pull request #10
Opened 2019-06-21 17:07 UTC by rjschwei

+ Config file to be processed changed to list of dicts from dict
    to handle same repo for multiple frameworks

2019-06-24 07:28 UTC, ikapelyukhin commented
Hmm, where has the config format changed?

2019-06-24 11:55 UTC, rjschwei commented
> Hmm, where has the config format changed?

In https://github.com/SUSE/pubcloud/pull/418

2019-06-24 12:05 UTC, ikapelyukhin commented
> > Hmm, where has the config format changed?
> 
> In [SUSE/pubcloud#418](https://github.com/SUSE/pubcloud/pull/418)

But it doesn't seem like `rmt_repos_config.json` format has changed there?

2019-06-24 12:46 UTC, rjschwei commented
> > > Hmm, where has the config format changed?
> > 
> > 
> > In [SUSE/pubcloud#418](https://github.com/SUSE/pubcloud/pull/418)
> 
> But it doesn't seem like `rmt_repos_config.json` format has changed there?

You are correct, forgot the PR that changes the format. 4 branches across 3 repos, one PR got lost :(

https://github.com/SUSE-Enceladus/update-infra-utils/pull/5

changes the format.

2019-06-25 01:17 UTC, bear454 approved these changes

2019-07-11 09:43 UTC, ikapelyukhin requested changes

2019-07-11 09:43 UTC, ikapelyukhin commented on check_rmt_repos
> +                del enabled_repos[id]
This is broken now because `config_repos` is an array now instead of a hash, a repo can be repeated more than once -- it will be deleted on the first encounter of the repo and report that the repo is missing next time it is encountered in the list.

2019-07-11 09:43 UTC, ikapelyukhin commented on check_rmt_repos
> +            if not enabled_repos.get(id):
It doesn't seem to be comparing host system framework vs. repo framework that's in the config anywhere -- it will complain about repos missing that belong to other frameworks.

2019-07-11 13:51 UTC, ikapelyukhin commented
@rjschwei let's use the description column (`repo_detail[2]`) -- repo arch is included in the description.
https://github.com/SUSE-Enceladus/monitoring/blob/f5032cfcf076cfab1c06d2082cb90dac5b35e9d6/check_rmt_repos#L50

2019-07-12 09:07 UTC, ikapelyukhin commented
It probably would be a good idea to make the output usable for cleaning up instances with config issues:
1. Output the list of space separated repo IDs that need to be disabled, so that they could be easily fed into `rmt-cli repos disable`.
2. Output a list of extra mirrored repo locations one per line, so that they can be removed easily.

2019-07-15 11:17 UTC, rjschwei commented
@ikapelyukhin suggesting implemented, still some other issues per e-mail

2019-07-15 12:37 UTC, ikapelyukhin commented on check_rmt_repos
> +    '--cloud',
Maybe we should detect it automatically, like we do in repo enablement script?

2019-07-15 15:36 UTC, rjschwei commented on check_rmt_repos
> +    '--cloud',
@ikapelyukhin The repo script is internal and therefore can be targeted to our specific use cases. However, we expect CSPs that run their own infrastructure to be able to use this public tool and therefore hard coding our use cases would work against the general purpose nature of this code.

2019-07-15 15:42 UTC, ikapelyukhin commented on check_rmt_repos
> +    '--cloud',
Yes, but:

* We have automatic detection in `enable-rmt-repos` script, which is also supposed to be usable by 3rd parties.
* This is a mandatory setting now -- it doesn't make any sense for 3rd party CSPs, as they are not operating it on multiple different frameworks. They don't have to explicitly set it in the product config at all, most likely they'll have to supply some random value for this script.
* This makes our monitoring configs CSP-specific.

Can we instead do auto-detection, and if no framework is detected -- ignore all framework-specific repos? That'd work for us and for 3rd party CSPs.

2019-07-15 15:44 UTC, ikapelyukhin commented on check_rmt_repos
> +    '--cloud',
Repo enablement script w/ autodetection isn't internal: https://github.com/SUSE-Enceladus/update-infra-utils/blob/master/update-server-repo-setup/enable-rmt-repos#L87-L94

2019-07-15 15:46 UTC, ikapelyukhin approved these changes
But other than the framework discussion -- LGTM. :+1:

2019-07-15 15:50 UTC, rjschwei commented on check_rmt_repos
> +    '--cloud',
Fair point and we have to fix this. However, a 3rd party CSP may still have multiple environments where different repositories get enabled. I'll rework the handling of the framework in both places. Thanks

2019-07-15 15:52 UTC, ikapelyukhin commented on check_rmt_repos
> +    '--cloud',
OK, requiring it to be set explicitly in the repo enablement script would also work. :slightly_smiling_face:

2019-07-18 22:22 UTC, merged