Refactor/fix check_proc_time_hang
SUSE-Enceladus/monitoring pull request #15
Opened 2019-08-16 13:47 UTC by ikapelyukhin

2019-08-16 19:30 UTC, rjschwei requested changes

2019-08-16 19:30 UTC, rjschwei commented on check_proc_timed_hang
> +    sys.exit(CRITICAL)
We wanted to make this `sys.exit('WARN')` so we turn icinga Yellow instead of Red if we want to not kill long running processes.

2019-08-19 09:59 UTC, ikapelyukhin commented on check_proc_timed_hang
> +    sys.exit(CRITICAL)
Fixed.

2019-08-19 11:58 UTC, rjschwei approved these changes

2019-08-19 11:58 UTC, merged