Monitor extra repos
SUSE-Enceladus/monitoring pull request #9
Opened 2019-06-14 14:08 UTC by ikapelyukhin

Adds monitoring the repos that are enabled in RMT but not defined in the repo config.

2019-06-14 17:39 UTC, rjschwei requested changes

2019-06-14 17:39 UTC, rjschwei commented on check_rmt_repos
> +
We also want to check if there are extra directories. We should not just check the data. For example, when we disable the SLES 11 repos by pulling them out of the configuration we want monitoring to complain that the packages are stilled stored on the servers.

2019-06-17 09:19 UTC, ikapelyukhin commented on check_rmt_repos
> +
@rjschwei Well, there are two problems with this, both require changes to RMT:

1. Repo paths aren't in the output of any CLI command, there's no reliable way to match a path on disk to a repo in the DB;
2. RMT should be able to reclaim disk space automatically (i.e., just ran the clean-up periodically, rather than monitor things). Old data clean up has been on RMT backlog since the beginning, currently there's no way to reclaim disk space other than removing files manually.

    It should be able to clean up both the old packages in the repos (that aren't referenced by the metadata once the updates are released) and the repos that have been disabled.

We could start with item 1 by adding repo URLs into RMT's output and monitoring with this script.

2019-06-17 15:53 UTC, ikapelyukhin commented
@rjschwei local paths are actually available from `repository_config.json`, so no changes to RMT are required. I've added monitoring of leftover repos.

2019-06-18 21:53 UTC, rjschwei approved these changes

2019-06-18 21:53 UTC, merged